EduPlatform/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings
from django.contrib.auth.urls import *

from EduPlatform import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('exercises/', include('exercises.urls', namespace='exercises')),
    path('users/', include('users.urls', namespace='users'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exercises/urls.py
import re

from django.urls import path
from exercises.views import exercises_list, exercise_page, add_text

app_name = 'exercises'

urlpatterns = [
    path('', exercises_list, name="exercises-list"),
    path('<slug:exercise_slug>/', exercise_page, name="exercise-page"),
    path('addtext', add_text, name="add_text"),
]

main/urls.py
from django.urls import path
from main.views import index

app_name = 'main'

urlpatterns = [
    path('', index, name="index"),
]

users/urls.py
from django.urls import path
from users.views import login_view, profile, options_list, useradd

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('profile/', profile, name="profile"),
    path('options/', options_list, name="options_list"),
    path('useradd/', useradd, name='useradd')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager

# Create your models here.
class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name="Аватар")

    class Meta:
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

users/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField()
    password = forms.PasswordInput()

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from users.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from users.models import User
from exercises.models import SystemImages


def login_view(request):
    if request.method == 'POST':
        form = UserForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                user = User.objects.get(username=username)
                return render(request, 'users/profile.html')
            else:
                form = UserForm()
    return render(request, "users/login.html")


@login_required(login_url="users:login")
def profile(request):
    user = request.user
    if request.GET.get('logout', 'false') == 'true':
        logout(request)
        return render(request, "users/login.html")
    data = {
        'request': request,
        'user': user
    }
    return render(request, "users/profile.html", data)


def options_list(request):
    return render(request, "users/options_list.html")


def useradd(request):
    if request.method == 'POST':
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password and confirm_password and password == confirm_password:
            user = User.objects.create_user(username, email, password)
            user.first_name = firstname
            user.last_name = lastname
            user.save()

            data = {
                'request': request,
                'user': user,
                'img_placeholder': SystemImages.objects.get(name="Profile_placeholder")
            }
            return render(request, "users/profile.html", data)
    return render(request, "users/useradd.html")

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block style %}

<link rel="stylesheet" href="{% static 'users/css/log_in.css' %}">
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock style %}

{% block content %}

<div class="form-wrapper">
    <div class="wrapper">
        <form action="{% url "users:login" %}" method="POST">
            {% csrf_token %}
            <h1>Вход</h1>
            <div class="input-box">
                <input name='username' type="text" placeholder="Имя пользователя" required>
                <i class='bx bxs-user'></i>
            </div>
            <div class="input-box">
                <input name='password' type="password" placeholder="Пароль" required>
                <i class='bx bxs-lock-alt'></i>
            </div>
            <div class="remember-fogot">
                <label><input type="checkbox">Запомнить меня</label>
                <a href="#">Забыли пароль?</a>
            </div>
            <button type="submit" class="btn">Войти</button>
            <!-- <div class="register-link">
                <p>Don't have and account? <a href="#">Register</a></p>
            </div> -->
        </form>
    </div>
</div>

{% endblock content %}

users/templates/users/options_list.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/options_list.css' %}">
<link rel="stylesheet" href="{% static 'users/css/options_user.css' %}">
<link rel="stylesheet" href="{% static 'users/css/options_text.css' %}">
{% endblock style %}

{% block content %}

<div class="content">
    <div class="options-list">
        <a class="option" onclick="switchForm('user');">Добавить пользователя</a>
        <a class="option" onclick="switchForm('text');">Добавить текст</a>
        <a class="option" onclick="switchForm('memo');">Добавить memo</a>
        <a class="option" onclick="switchForm('custom');">Персонализация</a>
        {% comment %} <a class="option" href="#"></a> {% endcomment %}
    </div>
    <div class="action-panel">
    
        <div class="user-form-container hidden" id="user-form-container">
            <form action="{% url "users:useradd" %}" method="POST">
                {% csrf_token %}
                <div class="input-cols">
                    <div class="input-group">
                        <input name='username' type="text" placeholder="Имя пользователя" required>
                        <input name='firstname' type="text" placeholder="Имя" required>
                        <input name='lastname' type="text" placeholder="Фамилия" required>
                    </div>
                    <div class="input-group">
                        <input name='email' type="text" placeholder="Адрес эл. почты" required>
                        <input name='password' type="password" placeholder="Пароль" required>
                        <input name='confirm_password' type="password" placeholder="Подтверждение пароля" required>
                    </div>
                </div>
                
                <div class="btn-container">
                    <button type="submit" class="btn">Создать</button>
                </div>
            </form>
        </div>
    
        <div class="text-form-container hidden" id="text-form-container">
            <form action="{% url "exercises:add_text" %}" method="POST">
                {% csrf_token %}
                <div class="input-group">
                    <input name="name" type="text" class="text_title" placeholder="Заголовок">
                    <textarea rows="20" name="content" type="text" class="text_content" placeholder="Текст"></textarea>
                </div>
                <div class="btn-container">
                    <button type="submit" class="btn">Добавить</button>
                </div>
            </form>
        </div>
            
        <div class="memo-form-container hidden" id="memo-form-container"></div>
        <div class="custom-form-container hidden" id="custom-form-container"></div>
    </div>
</div>

<script src="{% static "users/js/switch_form.js" %}"></script>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block style %}

<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />

{% endblock style %}

{% block content %}

<div class="profile-body">
    <div class="data-container">
        <div class="profile-picture-container">
            {% if user.image %}
            <div class="profile-picture" style="
                background-image: url('{{ user.image.url }}');
            ">            
            </div>
            {% else %}
                <div class="profile-picture" style="
                    background-image: url('{% static "users/images/default-avatar.png" %}');
                ">            
                </div>
            {% endif %}
        </div>
        <div class="profile-data">
            <div class="data-header-container">
                <div class="data-line"><p class="data-header">Никнейм:</p></div>
                <div class="data-line"><p class="data-header">Имя:</p></div>
                <div class="data-line"><p class="data-header">Фамилия:</p></div>
                <p class="data-header">Электронная почта:</p>
            </div>
            <div class="data-body-container">
                <div class="data-line"><p class="data-body">{{ user.username }}</p></div>
                <div class="data-line"><p class="data-body">{{ user.first_name }}</p></div>
                <div class="data-line"><p class="data-body">{{ user.last_name }}</p></div>
                <p class="data-body">{{ user.email }}</p>
            </div>
        </div>
    </div>
    <div class="manage-panel">
        {% if user.is_superuser %}
            <form action="{% url "users:profile" %}" method="GET">
                <input type="hidden" name="logout" value="true">
                <button type="submit" class="manage-option exit-menu">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h280v80H200Zm440-160-55-58 102-102H360v-80h327L585-622l55-58 200 200-200 200Z"/></svg>
                </button>
            </form>
            <a href="{% url "admin:index" %}" class="manage-option admin">
                <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M680-280q25 0 42.5-17.5T740-340q0-25-17.5-42.5T680-400q-25 0-42.5 17.5T620-340q0 25 17.5 42.5T680-280Zm0 120q31 0 57-14.5t42-38.5q-22-13-47-20t-52-7q-27 0-52 7t-47 20q16 24 42 38.5t57 14.5ZM480-80q-139-35-229.5-159.5T160-516v-244l320-120 320 120v227q-19-8-39-14.5t-41-9.5v-147l-240-90-240 90v188q0 47 12.5 94t35 89.5Q310-290 342-254t71 60q11 32 29 61t41 52q-1 0-1.5.5t-1.5.5Zm200 0q-83 0-141.5-58.5T480-280q0-83 58.5-141.5T680-480q83 0 141.5 58.5T880-280q0 83-58.5 141.5T680-80ZM480-494Z"/></svg>
            </a>
            <a href="{% url "users:options_list" %}" class="manage-option useradd">
                <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M440-280h80l12-60q12-5 22.5-10.5T576-364l58 18 40-68-46-40q2-14 2-26t-2-26l46-40-40-68-58 18q-11-8-21.5-13.5T532-620l-12-60h-80l-12 60q-12 5-22.5 10.5T384-596l-58-18-40 68 46 40q-2 14-2 26t2 26l-46 40 40 68 58-18q11 8 21.5 13.5T428-340l12 60Zm40-120q-33 0-56.5-23.5T400-480q0-33 23.5-56.5T480-560q33 0 56.5 23.5T560-480q0 33-23.5 56.5T480-400ZM200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-560H200v560Zm0-560v560-560Z"/></svg>
            </a>
        {% else %}
            <form action="{% url "users:profile" %}" method="GET">
                <input type="hidden" name="logout" value="true">
                <button type="submit" class="manage-option exit-single">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h280v80H200Zm440-160-55-58 102-102H360v-80h327L585-622l55-58 200 200-200 200Z"/></svg>
                </button>
            </form>
        {% endif %}
    </div>
</div>

{% endblock content %}

users/templates/users/useradd.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/useradd.css' %}">
{% endblock style %}

{% block content %}
<div class="form-wrapper">
    <div class="wrapper">
        <form action="{% url "users:useradd" %}" method="POST">
            {% csrf_token %}
            <h1>Добавление нового пользователя</h1>
            <div class="input-cols">
                <div class="input-group">
                    <div class="input-box">
                        <input name='username' type="text" placeholder="Имя пользователя" required>
                        <i class='bx bxs-user'></i>
                    </div>
                    <div class="input-box">
                        <input name='firstname' type="text" placeholder="Имя" required>
                        <i class='bx bxs-user'></i>
                    </div>
                    <div class="input-box">
                        <input name='lastname' type="text" placeholder="Фамилия" required>
                        <i class='bx bxs-user'></i>
                    </div>
                </div>
                <div class="input-group">
                    <div class="input-box">
                        <input name='email' type="text" placeholder="Адрес эл. почты" required>
                        <i class='bx bxs-user'></i>
                    </div>
                    <div class="input-box">
                        <input name='password' type="password" placeholder="Пароль" required>
                        <i class='bx bxs-lock-alt'></i>
                    </div>
                    <div class="input-box">
                        <input name='confirm_password' type="password" placeholder="Подтверждение пароля" required>
                        <i class='bx bxs-lock-alt'></i>
                    </div>
                </div>
            </div>
            
            <div class="btn-container">
                <button type="submit" class="btn">Создать</button>
            </div>
            <!-- <div class="register-link">
                <p>Don't have and account? <a href="#">Register</a></p>
            </div> -->
        </form>
    </div>
</div>
{% endblock content %}