EduPlatform/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings
from django.contrib.auth.urls import *

from EduPlatform import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('exercises/', include('exercises.urls', namespace='exercises')),
    path('users/', include('users.urls', namespace='users'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exercises/urls.py
import re

from django.urls import path
from exercises.views import exercises_list, exercise_page, add_text

app_name = 'exercises'

urlpatterns = [
    path('', exercises_list, name="exercises-list"),
    path('<slug:exercise_slug>/', exercise_page, name="exercise-page"),
    path('addtext', add_text, name="add_text"),
]

main/urls.py
from django.urls import path
from main.views import index

app_name = 'main'

urlpatterns = [
    path('', index, name="index"),
]

users/urls.py
from django.urls import path
from users.views import login_view, profile, options_list, useradd

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('profile/', profile, name="profile"),
    path('options/', options_list, name="options_list"),
    path('useradd/', useradd, name='useradd')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" id="html_id">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/base-styles/base-header.css' %}" />
    {% block style %}{% endblock style %}
    <script src="{% static 'js/base.js' %}"></script>
    <title>FunEdu</title>
  </head>
  <body id="body">
    <header id="header">
      <div class="header-container">
        {% comment %} <h1 class="" logo>FunEdu</h1> {% endcomment %}
        <nav>
          <ul class="sidebar">
            <li onclick=hideSidebar()><a href="#"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"/></svg></a></li>
            <li><a href="{% url "exercises:exercises-list" %}">Упражнения</a></li>
            <li class="" ><a href="{% url "users:profile" %}">Профиль</a></li>
            <li><a href="#">О платформе</a></li>
          </ul>

          <ul>
            <li><a href="{% url "main:index" %}">Главная</a></li>
            <li class="hideOnMobile" ><a href="{% url "exercises:exercises-list" %}">Упражнения</a></li>
            <li><a class="hideOnMobile" href="{% url "users:profile" %}">Профиль</a></li>
            <li class="hideOnMobile" ><a href="#">О платформе</a></li>
            <li class="menu-button" onclick=showSidebar() ><a href="#"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z"/></svg></a></li>
          </ul>
        </nav>
      </div>
    </header>

    {% block content %}{% endblock content %}
    

  </body>
</html>