EduPlatform/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings
from django.contrib.auth.urls import *

from EduPlatform import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('exercises/', include('exercises.urls', namespace='exercises')),
    path('users/', include('users.urls', namespace='users'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exercises/urls.py
import re

from django.urls import path
from exercises.views import exercises_list, exercise_page, add_text

app_name = 'exercises'

urlpatterns = [
    path('', exercises_list, name="exercises-list"),
    path('<slug:exercise_slug>/', exercise_page, name="exercise-page"),
    path('addtext', add_text, name="add_text"),
]

main/urls.py
from django.urls import path
from main.views import index

app_name = 'main'

urlpatterns = [
    path('', index, name="index"),
]

exercises/models.py
from django.db import models


class Exercises(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name="Упражнение")
    image = models.ImageField(upload_to='exercises_images', verbose_name="Изображение")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    templates_folder_name = models.CharField(max_length=40, default="in-develop-templates", verbose_name="Папка шаблонов")

    class Meta:
        db_table = 'exercises'
        verbose_name = 'упражнение'
        verbose_name_plural = 'Упражнения'

    def __str__(self):
        return self.name
    
class Texts(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Текст")

    class Meta:
        db_table = 'texts'
        verbose_name = 'текст'
        verbose_name_plural = 'тексты'
    
    def __str__(self):
        return self.name


class Modes(models.Model):
    name = models.CharField(verbose_name='Режим', max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Режим"
        verbose_name_plural = "Режимы"


class MemoItems(models.Model):

    class Level(models.IntegerChoices):
        First = 1, '1'
        Second = 2, '2'
        Third = 3, '3'
        Fourth = 4, '4'

    class Theme(models.IntegerChoices):
        RoadTransport = 1, 'Транспорт'
        Animals = 2, 'Животные'
        Travel = 3, 'Путешествие'
        Nature = 4, 'Природа'
        Music = 5, 'Музыка'
        Furniture = 6, 'Мебель'
        Landscape = 7, 'Пейзажи'
        Clothes = 8, 'Одежда'

    name = models.CharField(verbose_name='Название', max_length=100, blank=False)
    image = models.ImageField(upload_to='memo_items', verbose_name="Изображение", blank=False)
    level = models.IntegerField(verbose_name="Уровень", choices=Level.choices, unique=False, blank=True, default=Level.First)
    theme = models.IntegerField(verbose_name="Тема", choices=Theme.choices, unique=False, blank=True, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Memo-предмет"
        verbose_name_plural = "Memo-предметы"

    
class SystemImages(models.Model):
    name = models.CharField(verbose_name='Название', max_length=100, blank=False, unique=True)
    image = models.ImageField(upload_to='sys_img', verbose_name="Изображение", blank=False, default="user_placeholder.png")

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Системное изображение"
        verbose_name_plural = "Системные изображения"

exercises/forms.py
from django import forms


class TextForm(forms.Form):
    text = forms.CharField()
    mode = forms.CharField()


class FrForm(forms.Form):
    text = forms.CharField()


class MemoForm(forms.Form):
    quantity = forms.CharField()
    time = forms.CharField()


class ShulteForm(forms.Form):
    size = forms.CharField()
    type = forms.CharField()
    angle = forms.CharField()


class StrupForm(forms.Form):
    isTable = forms.CharField(empty_value='no')
    isWords = forms.CharField(empty_value='no')
    quantity = forms.CharField()
    time = forms.CharField()


class JoraForm(forms.Form):
    size = forms.CharField()


form_exercise_match = {
    "texts": TextForm,
    "skorochtenie": FrForm,
    "memo": MemoForm,
    "shulte-table": ShulteForm,
    "strup-test": StrupForm,
    "drakosha-zhora": JoraForm,
}

exercises/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from exercises.models import Exercises, Texts
from exercises.forms import form_exercise_match
from exercises.exercises_logic.exercise_data_collector import exercise_collector_match


templates_folder = ""


def exercises_list(request):
    exercises = Exercises.objects.all()
    context = {
        'exercises': exercises,
    }
    return render(request, "exercises/system-templates/exercises-list.html", context)


def exercise_page(request, exercise_slug):
    global templates_folder
    page_name = ""
    exercise = ""

    if request.method == "GET":
        exercise = Exercises.objects.get(slug=exercise_slug)

        templates_folder = exercise.templates_folder_name
        if templates_folder == "system-templates":
            page_name = "in-develop.html"
        else:
            page_name = "settings.html"

        context = {
            'exercise_data': exercise,
            'slug': exercise_slug
        }

    elif request.method == "POST":
        form = form_exercise_match[exercise_slug](data=request.POST)
        
        if form.is_valid():
            data = exercise_collector_match[exercise_slug](request.POST)
            context = {
                "slug": exercise_slug,
                "data": data,
            }
        page_name = "exe.html"
    try:
        return render(request, f"exercises/{templates_folder}/{page_name}", context)
    except Exception as e:
        return redirect("/")


def add_text(request):
    if request.method == "POST":
        try:
            Texts.objects.create(name=request.POST['name'], content=request.POST['content'])
            messages.info(request, "Текст успешно сохранён!")
        except Exception as e:
            messages.debug(request, e)
    return redirect("/users/options")

exercises/templates/exercises/shulte/exe.html
{% extends "base.html" %}
{% load static %}

{% block style %}

<link rel="stylesheet" href="{% static "exercises/css/shulte/exe.css" %}">

{% endblock style %}

{% block content %}
<input id="data" type="hidden" data-size="{{ data.size }}" data-angle="{{ data.angle }}">
<input id="data" type="hidden" data-angle="{{ data.angle }}">
<div class="upper-container">
    <div class="end-but-container upper-el">
        <a class="end-button" href="{% url "exercises:exercise-page" "shulte-table" %}">Завершить</a>
    </div>
    <div class="label-container upper-el">
        <p class="current-letter" id="current-letter"></p>
        <p class="current-letter time-passed" id="time-passed"></p>
    </div>
    <div class="upper-el"></div>
</div>


<div class="table" id="table">
    {% for item in data.unordered_array %}
    <div id="" class="cell" onclick="shulteGame(event)">
        <p class="label">{{ item }}</p>
    </div>
    {% endfor %}
    <div id="center" class="central-point"></div>
    {% for item in data.ordered_array %}
    <div class="hidden-cell">
        <p class="label">{{ item }}</p>
    </div>
    {% endfor %}
</div>

<script src="{% static "exercises/js/shulte/exe.js" %}"></script>

{% endblock content %}

exercises/templates/exercises/shulte/settings.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static "exercises/css/shulte/settings.css" %}">
<link rel="stylesheet" href="{% static "css/system-styles/input-range.css" %}">
<link rel="stylesheet" href="{% static 'css/system-styles/scroller.css' %}">
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
{% endblock style %}

{% block content %}

<form method="POST" class="form">
    {% csrf_token %}
    <div class="setting-container">
        <div class="mode">
            <label class="mode-label">Режим:</label>
            <p id="mode-selected" class="mode-selected">Цифры</p>
            <button class="mode-button" id="mode-button" type="button" onclick="showModeOptions()"><i id="mode-button-icon" class='bx bxs-down-arrow'></i></button>
            <div id="mode-options" class="mode-options">
                <p class="option-label">Цифры</p>
                <input name="type" value="nums" id="check1" class="option-input" type="checkbox" checked="True" onchange="changeMode(this)">

                <p class="option-label">Буквы</p>
                <input name="type" value="letters" id="check2" class="option-input" type="checkbox" onchange="changeMode(this)">
            </div>
        </div>

        <div class="quantity">
            <label class="quantity-label">Размер таблицы:</label>
            <div class="quantity-input-container">
                <button class="minus-button" type="button" onclick="minusSize()">-</button>
                <input name="size" class="quantity-input" type="number" id="size" min="3" max="7" value="4">
                <button class="plus-button" type="button" onclick="plusSize()">+</button>
            </div>
        </div>

        <div class="angle">
            <label class="angle-label">Угол:</label>
            <div class="angle-input-container">
                <button class="minus-button" type="button" onclick="minusAngle()">-</button>
                <input name="angle" class="angle-input" type="number" id="angle" min="-180" max="180" value="0">
                <button class="plus-button" type="button" onclick="plusAngle()">+</button>
            </div>
        </div>
    
        <button class="start-button" type="submit">Старт</button>
    </div>
    
</form>

<script src="{% static "exercises/js/shulte/settings.js" %}"></script>

{% endblock content %}